#!/usr/bin/env ruby

printf 'Environment [pmatrix]> '
environment = gets.chomp.strip
environment = 'pmatrix' if environment.empty?

puts 'Content (spaces, Ctrl+D ends):'

content = Array[]
loop do
  printf '> '
  line = gets || break
  content << line.chomp.split(' ')
end

printf "\n\\begin{#{environment}}"
printf content.map { |row| row.join('&') }.join('\\\\')
printf "\\end{#{environment}}\n"
